#!/usr/bin/env bash
# Web servers are the piece of software generating and serving html pages
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" sudo tee /var/www/html/index.html
sudo service nginx start
