#!/usr/bin/env bash
# Web servers are the piece of software generating and serving html pages
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "51i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
