#!/usr/bin/env bash
# Web servers are the piece of software generating and serving html pages
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "

frontend K_Server
        bind *:80
        default_backend K_web

backend K_web
        balance roundrobin
        option forwardfor
        server 739-web-01 34.74.254.89
        server 739-web-02 34.74.106.201
" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy start
