#!/usr/bin/env bash
# It generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root -p"$1" --all-databases > backup.sql
name=$(date '+%d-%m-%Y')
tar czfv "$name.tar.gz" backup.sql
