#!/usr/bin/env bash
# A bash script that gives information about holbertonschool file
holberton="holbertonschool"
if [ -e "$holberton" ]; then
	echo "holbertonschool file exists"
	if [ -s "$holberton" ]; then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f "$holberton" ]; then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
