#!/usr/bin/env bash
# A bash script that gives information about holbertonschool file
if test -f "$holbertonschool"; then
	echo "holbertonschool file exists"
	if ls "$holbertonschool"; then
		echo "holbertonschool file is not empty"
		if [ -f "$holbertonschool" ]; then
			echo "holbertonschool is a regular file"
		fi
	else
		echo "holbertonschool file is empty"
	fi
else
	echo "holbertonschool file does not exist"
fi
